In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import cosine_similarity as c_s
from sklearn.preprocessing import OneHotEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
df = pd.read_csv('final_restaurant.csv')

In [3]:
df

,Unnamed: 0,placeID,Rcuisine,Rpayment,parking_lot,latitude,longitude,name,address,city,state,country,price,Rambience,area
0,0,135109,Italian,cash,no,18.921785,-99.235350,Paniroles,Domingo 10 711 El Empleado,Cuernavaca,Morelos,Mexico,medium,quiet,closed
1,1,135106,Mexican,cash,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
2,2,135106,Mexican,VISA,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
3,3,135106,Mexican,MasterCard-Eurocard,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
4,4,135104,Mexican,cash,yes,23.752982,-99.168434,vips,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,medium,familiar,closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,210,132608,Mexican,cash,public,23.758805,-99.165130,Hamburguesas La perica,cd. mier,Ciudad Victoria,Tamaulipas,Mexico,low,quiet,open
211,211,132594,Mexican,cash,public,23.752168,-99.165709,tacos de barbacoa enfrente del Tec,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,low,familiar,open
212,212,132584,Mexican,cash,yes,23.752365,-99.165288,Gorditas Dona Tota,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,medium,familiar,closed
213,213,132572,Cafeteria,cash,yes,22.141647,-100.992712,Cafe Chaires,Lateral Salvador Nava Martinez 3145,San Luis Potosi,San Luis Potosi,Mexico,low,familiar,closed
214,214,132560,Regional,cash,public,23.752304,-99.166913,puesto de gorditas,frente al tecnologico,Ciudad Victoria,Tamaulipas,Mexico,low,familiar,open

In [7]:
df['placeID'].nunique()

85

In [6]:
cusines = pd.read_csv('chefmozcuisine.csv')
cusines.nunique()

index       916
placeID     769
Rcuisine     59
dtype: int64

In [5]:
df['Rcuisine']

0        Italian
1        Mexican
2        Mexican
3        Mexican
4        Mexican
         ...
210      Mexican
211      Mexican
212      Mexican
213    Cafeteria
214     Regional
Name: Rcuisine, Length: 215, dtype: object

In [16]:
new_res_df = df.copy()
new_res_df['placeID'] = pd.factorize(df['placeID'])[0]+1
new_res_df

,Unnamed: 0,placeID,Rcuisine,Rpayment,parking_lot,latitude,longitude,name,address,city,state,country,price,Rambience,area
0,0,1,Italian,cash,no,18.921785,-99.235350,Paniroles,Domingo 10 711 El Empleado,Cuernavaca,Morelos,Mexico,medium,quiet,closed
1,1,2,Mexican,cash,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
2,2,2,Mexican,VISA,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
3,3,2,Mexican,MasterCard-Eurocard,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
4,4,3,Mexican,cash,yes,23.752982,-99.168434,vips,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,medium,familiar,closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,210,81,Mexican,cash,public,23.758805,-99.165130,Hamburguesas La perica,cd. mier,Ciudad Victoria,Tamaulipas,Mexico,low,quiet,open
211,211,82,Mexican,cash,public,23.752168,-99.165709,tacos de barbacoa enfrente del Tec,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,low,familiar,open
212,212,83,Mexican,cash,yes,23.752365,-99.165288,Gorditas Dona Tota,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,medium,familiar,closed
213,213,84,Cafeteria,cash,yes,22.141647,-100.992712,Cafe Chaires,Lateral Salvador Nava Martinez 3145,San Luis Potosi,San Luis Potosi,Mexico,low,familiar,closed
214,214,85,Regional,cash,public,23.752304,-99.166913,puesto de gorditas,frente al tecnologico,Ciudad Victoria,Tamaulipas,Mexico,low,familiar,open

In [9]:
users = pd.read_csv('userProfileDetail.csv')

In [11]:
users['userID'].nunique()

133

In [12]:
df_ratings = pd.read_csv('final_ratings.csv')

In [14]:
df_ratings.columns

Index(['index', 'userID', 'placeID', 'rating', 'food_rating',
       'service_rating'],
      dtype='object')

In [15]:
df_ratings['userID'].nunique()

136

In [17]:
new_user_df = df_ratings.copy()
new_user_df['userID'] = pd.factorize(new_user_df['userID'])[0]+1

In [20]:
new_user_df.sort_values(ascending=False, by=['userID'])

     index  userID  placeID  rating  food_rating  service_rating
812   1157     136   132715       1            1               0
809   1152     136   132717       2            2               1
811   1155     135   132732       1            1               1
810   1153     135   132613       1            1               1
808   1151     135   132609       1            2               1
..     ...     ...      ...     ...          ...             ...
3        4       2   135104       1            1               2
1        2       1   132825       2            2               2
264    433       1   135027       0            1               1
2        3       1   135060       1            2               2
0        0       1   135085       2            2               2

[815 rows x 6 columns]

In [25]:
new_user_df.groupby('userID').count()['rating']

userID
1      4
2      5
3      5
4      6
5      2
      ..
132    2
133    1
134    2
135    4
136    2
Name: rating, Length: 136, dtype: int64

In [29]:
new_user_df['placeID'].nunique()

85

In [30]:
new_user_df['placeID'] = pd.factorize(new_user_df['placeID'])[0]+1
new_user_df

     index  userID  placeID  rating  food_rating  service_rating
0        0       1        1       2            2               2
1        2       1        2       2            2               2
2        3       1        3       1            2               2
3        4       2        4       1            1               2
4        5       2        5       0            0               0
..     ...     ...      ...     ...          ...             ...
810   1153     135       10       1            1               1
811   1155     135        6       1            1               1
812   1157     136       15       1            1               0
813   1158       2        8       1            1               0
814   1159       2       17       1            1               1

[815 rows x 6 columns]

In [ ]:
new_user_df[new_user_df['userID']]

In [32]:
user_place_ratings = new_user_df.groupby('userID').agg(
    num_places_rated=('placeID', 'nunique'),      # Count of unique place IDs
    rated_place_ids=('placeID', lambda x: list(x.unique()))  # List of unique place IDs
)
user_place_ratings

        num_places_rated       rated_place_ids
userID
1                      4         [1, 2, 3, 55]
2                      5      [4, 5, 6, 8, 17]
3                      5       [7, 8, 6, 4, 9]
4                      6  [7, 6, 10, 11, 4, 8]
5                      2                [7, 8]
...                  ...                   ...
132                    2              [19, 38]
133                    1                  [19]
134                    2              [19, 38]
135                    4       [13, 14, 10, 6]
136                    2              [16, 15]

[136 rows x 2 columns]

In [34]:
new_res_df['Rcuisine'].unique()

array(['Italian', 'Mexican', 'Cafeteria', 'Burgers', 'Fast_Food',
       'Chinese', 'Seafood', 'Contemporary', 'Bar', 'Bar_Pub_Brewery',
       'Japanese', 'Pizzeria', 'Cafe-Coffee_Shop', 'American',
       'Breakfast-Brunch', 'Bakery', 'International', 'Game', 'Family',
       'Vietnamese', 'Armenian', 'Regional'], dtype=object)

In [35]:
new_res_df.to_csv('final_final_res.csv')
new_user_df.to_csv('final_final_ratings.csv')

In [36]:
new_res_df

,Unnamed: 0,placeID,Rcuisine,Rpayment,parking_lot,latitude,longitude,name,address,city,state,country,price,Rambience,area
0,0,1,Italian,cash,no,18.921785,-99.235350,Paniroles,Domingo 10 711 El Empleado,Cuernavaca,Morelos,Mexico,medium,quiet,closed
1,1,2,Mexican,cash,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
2,2,2,Mexican,VISA,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
3,3,2,Mexican,MasterCard-Eurocard,no,22.149709,-100.976093,El Rincón de San Francisco,Universidad 169,San Luis Potosi,San Luis Potosi,Mexico,medium,familiar,open
4,4,3,Mexican,cash,yes,23.752982,-99.168434,vips,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,medium,familiar,closed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,210,81,Mexican,cash,public,23.758805,-99.165130,Hamburguesas La perica,cd. mier,Ciudad Victoria,Tamaulipas,Mexico,low,quiet,open
211,211,82,Mexican,cash,public,23.752168,-99.165709,tacos de barbacoa enfrente del Tec,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,low,familiar,open
212,212,83,Mexican,cash,yes,23.752365,-99.165288,Gorditas Dona Tota,Calle Mezquite Fracc Framboyanes,Ciudad Victoria,Tamaulipas,Mexico,medium,familiar,closed
213,213,84,Cafeteria,cash,yes,22.141647,-100.992712,Cafe Chaires,Lateral Salvador Nava Martinez 3145,San Luis Potosi,San Luis Potosi,Mexico,low,familiar,closed
214,214,85,Regional,cash,public,23.752304,-99.166913,puesto de gorditas,frente al tecnologico,Ciudad Victoria,Tamaulipas,Mexico,low,familiar,open

In [37]:
new_res_df[['placeID', 'name', 'address']].drop_duplicates().sort_values(ascending=True, by='placeID').head(4)

   placeID                        name                           address
0        1                   Paniroles        Domingo 10 711 El Empleado
1        2  El Rincón de San Francisco                   Universidad 169
4        3                        vips  Calle Mezquite Fracc Framboyanes
7        4           Cafeteria cenidet     Interior Internado Palmira SN